#!/usr/bin/env zsh

DEVICES=$(tailscale status --json | jq -r '.Peer[] | select(.Online==true) | "\(.HostName) \(.TailscaleIPs[0])"')

SELECTED=$(echo "$DEVICES" | fzf --prompt="Select device " --height 10)

if [ -z "$SELECTED" ]; then
  echo "nothing selected..."
  exit 1
fi

CONNECT=$(echo "$SELECTED" | awk '{print $1}')
echo "connecting"

ssh $USER@$CONNECT
